openapi: 3.0.3
info:
  title: E-Commerce API
  description: API specification for E-Commerce
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
tags:
  - name: Product API
    description: Handles product management such as show the products, update it, delete it, etc.
paths:
  /api/v1/products:
    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - Product API
      requestBody:
        description: Required data to create a new product
        content:
          application/json:
            schema:
              required:
                - name
                - quantity
                - price
              type: object
              properties:
                name:
                  type: string
                  minLength: 3
                quantity:
                  type: integer
                  minimum: 0
                price:
                  type: number
                  format: float
                  minimum: 0
                description:
                  type: string
              example:
                name: Kinera Celest Wyvern White
                quantity: 11
                price: 528.993
                description: Garansi resmi 1 tahun
      responses:
        "201":
          description: Success create a new product
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Success create the product
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                      name:
                        type: string
                      quantity:
                        type: integer
                      price:
                        type: number
                        format: float
                      description:
                        type: string
                    example:
                      id: dcc02b52-a93e-4326-ae81-d1560f3b91d3
                      name: Kinera Celest Wyvern White
                      quantity: 11
                      price: 528.993
                      description: Garansi resmi 1 tahun
