openapi: 3.0.3
info:
  title: E-Commerce API
  description: API specification for E-Commerce
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
tags:
  - name: Product API
    description: Handles product management such as show the products, update it, delete it, etc.
paths:
  /api/v1/products:
    post:
      summary: Create a new product
      operationId: createProduct
      tags:
        - Product API
      requestBody:
        $ref: "#/components/requestBodies/CreateProduct"
      responses:
        "201":
          $ref: "#/components/responses/CreateProductSuccess"
        "400":
          $ref: "#/components/responses/CreateProductBadRequest"
        "401":
          $ref: "#/components/responses/CreateProductUnauthorized"
        "403":
          $ref: "#/components/responses/CreateProductForbidden"
        "500":
          $ref: "#/components/responses/InternalServerError"
components:
  schemas:
    ProductBase:
      description: Product base schema
      type: object
      required:
        - name
        - quantity
        - price
      properties:
        name:
          type: string
          minLength: 3
          maxLength: 150
          example: Kinera Celest Wyvern White
        quantity:
          type: integer
          minimum: 0
          example: 11
        price:
          type: integer
          description: In Rupiah (Rp)
          minimum: 0
          example: 500000
        description:
          type: string
          minLength: 3
          maxLength: 2000
          example: Garansi resmi 1 tahun
    CreateProductRequest:
      $ref: "#/components/schemas/ProductBase"
    Product:
      description: Product data
      allOf:
        - $ref: "#/components/schemas/ProductBase"
        - type: object
          properties:
            id:
              type: string
              format: uuid
              example: dcc02b52-a93e-4326-ae81-d1560f3b91d3
          required:
            - id
    CreateProductBadRequestResponse:
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: INVALID_INPUT
            message:
              type: string
              example: Invalid request body
            fields:
              type: object
              additionalProperties:
                type: string
    UnauthorizedResponse:
      description: Unauthorized response schema
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: UNAUTHORIZED
            message:
              type: string
              example: Unauthorized user. Please log in to an existing user or register a new user
    ForbiddenResponse:
      description: Forbidden response schema
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: FORBIDDEN
            message:
              type: string
              example: Forbidden access. You're not allowed to do this operation
    InternalServerErrorResponse:
      description: Internal server error response schema
      type: object
      properties:
        error:
          type: object
          properties:
            code:
              type: string
              example: INTERNAL_SERVER_ERROR
            message:
              type: string
              example: We're sorry your operation can't be executed during this time due to internal problem. Please try again later

  requestBodies:
    CreateProduct:
      description: Create product request body
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateProductRequest"

  responses:
    CreateProductSuccess:
      description: Success create a new product
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    CreateProductBadRequest:
      description: Failed to create a new product caused by invalid request body
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/CreateProductBadRequestResponse"
    CreateProductUnauthorized:
      description: Failed to create a new product caused by unauthorized user
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/UnauthorizedResponse"
    CreateProductForbidden:
      description: Failed to create a new product caused by forbidden access
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ForbiddenResponse"
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InternalServerErrorResponse"
